#!/bin/bash

## Set GTK Themes, Icons, Cursor and Fonts

THEME='gruvbox-light-soft'
ICONS='Tela-circle-purple'
FONT='Roboto 11'
CURSOR='Comix-Cursor-original-Red-Slim'

SCHEMA='gsettings set org.gnome.desktop.interface'

apply_themes() {
	${SCHEMA} gtk-theme "$THEME"
	${SCHEMA} icon-theme "$ICONS"
	${SCHEMA} cursor-theme "$CURSOR"
	${SCHEMA} font-name "$FONT"
}

apply_themes